### ISSUE TITLE
Error when disabling Phrase match

### ISSUE THREAD

**Issue by smoi** [Smile-SA/smile-magento-elasticsearch#46] opened 2016-01-05 15:01 UTC
If I disable the Phrase match feature I get this error 

"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[8n50abZmRyWXU6aR3ghgNA][alias-20160105-104205][0]: SearchParseException[[alias-20160105-104205][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must\":[null]}}]}},\"filter\":{\"bool\":{\"must\":[{\"terms\":{\"visibility\":[3,4]}},{\"terms\":{\"status\":[1]}},{\"terms\":{\"in_stock\":[1]}},{\"fquery\":{\"query\":{\"query_string\":{\"query\":\"(categories:2) OR (show_in_categories:2)\"}},\"_cache\":true}},{\"terms\":{\"store_id\":[1]}}],\"_cache\":true}}}},\"facets\":{\"attribute_set_id\":{\"terms\":{\"size\":9,\"order\":\"count\",\"field\":\"attribute_set_id\"}}},\"from\":0,\"size\":0}]]]; nested: QueryParsingException[[alias-20160105-104205] [_na] query malformed, must start with start_object]; }]","status":400}

i'm also facing an issue, we are a wine ecommerce, if I search for champagne I get results for prosecco and other things which are not champagne. Is this something related to phonetic or something?

**Comment by romainruaud** [comment] 2016-02-08 16:43
I'm not able to reproduce your issue.

Can you precise more informations ? Especially your version of Magento, and your module configuration if you did modify the default values.

Best regards,

**Comment by afoucret** [comment] 2016-03-07 14:59
I will close it since it haven't moved for a while and I suspect it to be resolved.
Feel free to reopen if the issue is still present.

**Closed by afoucret** 2016-03-07 14:59 UTC
