### ISSUE TITLE
Search results not found

### ISSUE THREAD

**Issue by Chris25602** [Smile-SA/smile-magento-elasticsearch#15] opened 2015-05-28 15:47 UTC
So all of the bells and whistles seem to work fine. And I can tell the quick search is hitting ES because the autocomplete shows data but unless I choose a category or product I end up at 'domain/catalogsearch/html' 404

**Comment by afoucret** [comment] 2015-06-25 05:51
Are all your indexer ok in the admin area ?
If not try to reindex all.

What version of Magento ?

**Comment by Chris25602** [comment] 2015-07-16 19:26
I am on Magento ver. 1.14.0.1. And no, my 'catalog_url_category' index throws a fatal PHP error, otherwise they are all in good order. Its something about calling a non-object and Set Flat Category. I am not sure how this would be connected but, it probably is.

**Comment by afoucret** [comment] 2015-09-14 18:04
The module is not compatible with Flat Categories (explain in #6).
I should take some time to update the documentation.

**Comment by afoucret** [comment] 2015-09-16 04:45
As explain in #16, I change my mind with flat categories and have implemented their support.
Please, can you test again and confirm your issue was related.

**Comment by afoucret** [comment] 2015-10-05 17:51
Any status on this ?
Should I close the issue ?

**Comment by afoucret** [comment] 2016-03-07 14:56
I will close it since it haven't moved for a while and I suspect it to be resolved.
Feel free to reopen if the issue is still present.

**Closed by afoucret** 2016-03-07 14:56 UTC
Labels: question
