### ISSUE TITLE
Unable to use attributes with hyphens

### ISSUE THREAD

**Issue by Demoli** [Smile-SA/smile-magento-elasticsearch#25] opened 2015-08-21 15:54 UTC
We have some size attributes which contain hyphens as part of the label, these are indexed by elastic just fine, but when we try to run a query on one, we get no results.

Example query:
```
?size[0]=X-Large
```
This becomes X\\-Large in the query.

It seems that hyphens are always escaped in
```
Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Query_Abstract::_escape
```
Is it possible to have hyphenated attribute values with this module?

**Comment by nicosomb** [comment] 2015-08-27 15:22
Hello @Demoli, 

I don't reproduce this problem. 
But if I click on "X-Large" (which seems to have one product), I get 0 product (There are no products matching the selection). 

I'll try to fix it.

**Comment by nicosomb** [comment] 2015-08-28 08:11
Hello @Demoli, 

As it's written [in Elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters), some characters are reserved (`+ - = && || > < ! ( ) { } [ ] ^ " ~ * ? : \ /`).

Before we fix this bug, you can temporarily rename your attribute value by removing the hyphen.

**Comment by cvalcke** [comment] 2015-09-14 09:03
Hello,
I have exactly the same problem and what I do not understand is why we shouldn't have to escape reserved characters with a value of type "sentence" (in this case we are using escapePhrase() instead of escape() thanks to \Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Query_Abstract::prepareFilterQueryText method)

**Comment by afoucret** [comment] 2015-09-14 17:34
Should have been fixed at commit 7c8045c1dd2ecc50cc9ede7e54dc552d4b478ed7
Let us know if it is OK for you.

**Comment by cvalcke** [comment] 2015-09-15 06:30
It works for me thanks. It's not too heavy to remove character escaping on term filtering ?

**Comment by afoucret** [comment] 2015-09-15 08:50
No risk at all since the match query does the escaping for us.
Can become a product in query_string but escaping has been kept in this context.

I close the issue.

Thank you for your feedback.

**Closed by afoucret** 2015-09-15 08:50 UTC
Labels: bug
