### ISSUE TITLE
Call to undefined method Smile_ElasticSearch_Helper_Data::getAttributeFieldName()

### ISSUE THREAD

**Issue by Swahjak** [Smile-SA/smile-magento-elasticsearch#31] opened 2015-09-22 14:47 UTC
```
Fatal error: Call to undefined method Smile_ElasticSearch_Helper_Data::getAttributeFieldName() in app/code/community/Smile/ElasticSearch/Model/Catalog/Layer/Filter/Decimal.php on line 135
```

https://github.com/Smile-SA/smile-magento-elasticsearch/blob/master/src/app/code/community/Smile/ElasticSearch/Model/Catalog/Layer/Filter/Decimal.php#L135

**Comment by afoucret** [comment] 2015-09-22 15:25
Duplicate of #27, so I close this one.

FYI : the patch is coming very soon !!!

**Closed** 2015-09-22 15:25 UTC

**Comment by Swahjak** [comment] 2015-09-22 15:37
@afoucret just to be sure (asume if you are working on this you caught this error as well):
```
Fatal error: Call to undefined method Smile_ElasticSearch_Model_Resource_Catalog_Product_Collection::getExtendedSearchParams() in /home/topperroot/vendor/smile/elasticsearch/src/app/code/community/Smile/ElasticSearch/Model/Catalog/Layer/Filter/Decimal.php on line 106
```
