### ISSUE TITLE
install-es.sh on Ubuntu 16.04

### ISSUE THREAD

**Issue by Chris25602** [Smile-SA/smile-magento-elasticsearch#76] opened 2016-06-24 02:06 UTC
It breaks...I fixed my install by uncommenting the line 

in etc/default/elasticsearch 
START_DAEMON=true

That fixes es but I had to finish all the es module config by hand...not a huge deal but a bit more time than I was expecting. Not complaining just informing.

**Comment by acidreian666** [comment] 2016-08-09 02:04
@Chris25602  I'm not quite fallowing how to reproduce this issue but I fallowed the guide here and I use Ubuntu 16.04 and had zero issues.

**Comment by romainruaud** [comment] 2016-10-11 07:35
Yes, the install script was meant for debian and I guess it was on Wheezy. So the script is not handling specificities of systemd based recent versions of Debian and/or Ubuntu.

Thank you for reporting it. I close the issue since you resolved your problem.

Best regards,

**Closed by romainruaud** 2016-10-11 07:35 UTC
