### ISSUE TITLE
Fatal error: Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex()

### ISSUE THREAD

**Issue by drosanda** [Smile-SA/smile-magento-elasticsearch#22] opened 2015-07-22 03:33 UTC
Dear All, 

I have facing this error while trying to reindex.

Magento CE 1.9.1.0

Fatal error: Call to undefined method Mage_CatalogSearch_Model_Resource_Fulltext_Engine::getCurrentIndex() in app\code\community\Smile\ElasticSearch\Model\Indexer\Fulltext.php on line 182

Thanks

**Comment by nicosomb** [comment] 2015-07-27 12:32
Hello, 

Your issue is a duplicate of #10.

**Closed by nicosomb** 2015-07-27 12:32 UTC
Labels: duplicate
