### ISSUE TITLE
Problems indexing

### ISSUE THREAD

**Issue by tacheshun** [Smile-SA/smile-magento-elasticsearch#5] opened 2015-02-19 23:48 UTC
Hello,
After a succesful installation of the module, I tried re-indexing Catalog Search Index. The output is this:
```
{"error":"MapperParsingException[mapping [product]]; nested: MapperParsingException[Analyzer [analyzer_zh] not found for field [options_shoe_type_zh]]; ","status":400}
Cannot initialize the indexer process.
```
Also, the exception.log looks like this:
```
2015-02-19T23:13:29+00:00 ERR (3): 
exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://lofty-dev.lofty.com:9200/dev-20150219-231329' in /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vagrant/LoftySite/magento/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /vagrant/LoftySite/magento/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 /vagrant/LoftySite/magento/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 /vagrant/LoftySite/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 /vagrant/LoftySite/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#17 /vagrant/LoftySite/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/dev-20150219-2...', Array, '{"settings":{"n...')
#18 /vagrant/LoftySite/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/dev-20150219-2...', Array, Array)
#19 /vagrant/LoftySite/magento/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 /vagrant/LoftySite/magento/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(236): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#21 /vagrant/LoftySite/magento/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(306): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#22 /vagrant/LoftySite/magento/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#23 /vagrant/LoftySite/magento/app/code/core/Mage/Index/Model/Process.php(210): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#24 /vagrant/LoftySite/magento/app/code/core/Mage/Index/Model/Process.php(258): Mage_Index_Model_Process->reindexAll()
#25 /vagrant/LoftySite/magento/app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(182): Mage_Index_Model_Process->reindexEverything()
#26 /vagrant/LoftySite/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Index_Adminhtml_ProcessController->massReindexAction()
#27 /vagrant/LoftySite/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('massReindex')
#28 /vagrant/LoftySite/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Magnify_Mobile_Http))
#29 /vagrant/LoftySite/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#30 /vagrant/LoftySite/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#31 /vagrant/LoftySite/magento/index.php(85): Mage::run('', 'store')
#32 {main}
```

Thank you.

**Comment by afoucret** [comment] 2015-02-20 05:05
Hello @tacheshun,

Thank you for reporting this issue.

The problem is that chinese is not supported at this time. I should be able to provide a patch that make indexing functionnal with chinese very soon. But it will only be a technical patch that make things work again when a chinese website is present.

To be fully honest, we didn't work a lot on non-european languages support yet because we do not deal with them very often. So the result can be a little desappointing as a matter of relevancy. So it would be great if you can test relevancy and if you give a feedback on this implementation once done.

I keep you noticed when the "technical patch" will be available.

**Comment by markus-g** [comment] 2015-02-23 13:51
Hello @afoucret,

I've got nearly the same issue:

```
{"error":"MapperParsingException[mapping [product]]; nested: MapperParsingException[Analyzer [analyzer_] not found for field [options_options_container_]]; ","status":400}
        Fehler beim Neuaufbau.
```
And here my exception log
```

2015-02-23T13:46:59+00:00 ERR (admin): cli D:\xampp\php\n98-magerun.phar
REQUEST: -
TIME: 4.520258s
ADDRESS: -
USER AGENT: -
FILE: D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Resource\Engine\Elasticsearch\Index.php:239

exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://127.0.0.1:9200/project_name-20150223-134658' in D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Exception\BadResponseException.php:43
Stack trace:
#0 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Message\Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Message\Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Message\Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Message\EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Curl\CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Curl\CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Curl\CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Curl\CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Curl\CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Curl\CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\guzzle\http\Guzzle\Http\Message\Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#17 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/project_name-20150...', Array, '{"settings":{"n...')
#18 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Endpoints\AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/project_name-20150...', Array, Array)
#19 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Namespaces\IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Resource\Engine\Elasticsearch\Index.php(236): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#21 D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Resource\Engine\Elasticsearch\Index.php(306): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#22 D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Indexer\Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#23 D:\xampp-5.5.19\htdocs\project_name\app\code\core\Mage\Index\Model\Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#24 D:\xampp-5.5.19\htdocs\project_name\app\code\core\Mage\Index\Model\Process.php(260): Mage_Index_Model_Process->reindexAll()
#25 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Command/Indexer/ReindexCommand.php(104): Mage_Index_Model_Process->reindexEverything()
#26 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): N98\Magento\Command\Indexer\ReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(427): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(882): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(N98\Magento\Command\Indexer\ReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Application.php(523): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(126): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Application.php(583): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 D:\xampp-5.5.19\php\n98-magerun.phar(8): N98\Magento\Application->run()
#34 {main}

Next exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":"MapperParsingException[mapping [product]]; nested: MapperParsingException[Analyzer [analyzer_] not found for field [options_options_container_]]; ","status":400}' in D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php:266
Stack trace:
#0 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"settings":{"n...')
#1 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#2 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/project_name-20150...', Array, '{"settings":{"n...')
#3 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Endpoints\AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/project_name-20150...', Array, Array)
#4 D:\xampp-5.5.19\htdocs\project_name\lib\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Namespaces\IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Resource\Engine\Elasticsearch\Index.php(236): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#6 D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Resource\Engine\Elasticsearch\Index.php(306): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#7 D:\xampp-5.5.19\htdocs\project_name\app\code\community\Smile\ElasticSearch\Model\Indexer\Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#8 D:\xampp-5.5.19\htdocs\project_name\app\code\core\Mage\Index\Model\Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#9 D:\xampp-5.5.19\htdocs\project_name\app\code\core\Mage\Index\Model\Process.php(260): Mage_Index_Model_Process->reindexAll()
#10 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Command/Indexer/ReindexCommand.php(104): Mage_Index_Model_Process->reindexEverything()
#11 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): N98\Magento\Command\Indexer\ReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(427): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(882): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(N98\Magento\Command\Indexer\ReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Application.php(523): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar://D:/xampp-5.5.19/php/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(126): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar://D:/xampp-5.5.19/php/n98-magerun.phar/src/N98/Magento/Application.php(583): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 D:\xampp-5.5.19\php\n98-magerun.phar(8): N98\Magento\Application->run()
#19 {main}
```
The shop doesn't use any chinese, but german letters.
I tried it on Windows 7 with elasticsearch 1.4.4.

Thank you for your help.

**Comment by afoucret** [comment] 2015-02-25 12:18
You can try again for both chinese and german since the issue has been fixed at the rev. 1126ac4d23c824e45404f39a64effb4d0d7dc0f5.

@tacheshun, as explained earlier, the result might disapointing in matter of relevance of the results with Chinese. I am very interested in having a feedback from you on this point.

@markus-g co The german is fixed can you tell me if it is OK for you. One more question : is your website using a variation of german (just like de_AT or something like that) ?

**Comment by markus-g** [comment] 2015-02-26 10:00
Thank you afoucret, it's working now!

The shop uses a separate website for de_DE, de_AT (currently not active) and de_CH, each with the matching locale.
Most differences are only in product prices, delivery times and CMS content. Product and category names are all the same.

**Comment by afoucret** [comment] 2015-02-26 10:06
@markus-g The real problem was de_CH language not supported until I fixed.
That is why I ask you about your exact language setup.
The new version is using de as a generic language and do not pay attention to variation (it is not a problem as language analysis is the same for all variation of a language).

I wait for @tacheshun feedback about language that can not use snowball analyzer to close the issue.

**Comment by tacheshun** [comment] 2015-02-26 12:28
@afoucret works for me too!
Thank you!

**Comment by afoucret** [comment] 2015-02-26 18:01
Thx for the feedback.

**Closed by afoucret** 2015-02-26 18:01 UTC
Labels: bug
