### ISSUE TITLE
Error when enable module smile elasticsearch

### ISSUE THREAD

**Issue by bacnl** [Smile-SA/smile-magento-elasticsearch#13] opened 2015-05-13 04:11 UTC
Hi,
I enable module smile elasticsearch in admin configuration , flush cache , reindex
i reload the frontend homepage when i access submenu bar or type in search box, it not show anything , i get blank page 
When i disable this module and enable mysql fulltext , everything Ok
I install magento 1.9.1 CE and elasticsearch 1.4
Please help me 
![blankpage](https://cloud.githubusercontent.com/assets/3671450/7603628/d151167c-f960-11e4-894f-73237ecf27a3.PNG)
![blankpage2](https://cloud.githubusercontent.com/assets/3671450/7603626/d09e0514-f960-11e4-95ec-f14eac51200f.PNG)
![config](https://cloud.githubusercontent.com/assets/3671450/7603630/d1532fd4-f960-11e4-8501-42b5caef8adc.PNG)
![error](https://cloud.githubusercontent.com/assets/3671450/7603627/d145fa4e-f960-11e4-91da-f4d0bd53f4e1.PNG)
![searchresault](https://cloud.githubusercontent.com/assets/3671450/7603629/d1519b56-f960-11e4-9475-d586952dba1e.PNG)

**Comment by afoucret** [comment] 2015-06-25 05:50
Did you reindex your catalog after you get the configuration has been changed ?

**Comment by nicosomb** [comment] 2015-06-30 13:27
Hello @bacnl!

You said you install ES 1.4, but this module supports ES >= 1.5.
Can you upgrade your ES installation please? 
What do you see when you go here: http://127.0.0.1:9200? Are you sure ES is installed behind this IP or behind the same IP than your webserver (52.74.68.56)?

**Comment by afoucret** [comment] 2015-09-14 18:16
Is the issue still alive ?

**Comment by afoucret** [comment] 2015-10-05 17:51
Any status on this ?
Should I close the issue ?

**Comment by afoucret** [comment] 2016-03-07 14:56
I will close it since it haven't moved for a while and I suspect it to be resolved.
Feel free to reopen if the issue is still present.

**Closed by afoucret** 2016-03-07 14:56 UTC
Labels: question
