### ISSUE TITLE
product listing on category pages

### ISSUE THREAD

**Issue by opencubicles** [Smile-SA/smile-magento-elasticsearch#77] opened 2016-09-01 10:12 UTC
Noticed that after the installation of this extension, the product listing on category pages is getting affected by this plugin. Is there any away to avoid that?

We want this extension to affect only search feature on the website only.

**Comment by romainruaud** [comment] 2016-09-01 10:25
Hello @opencubicles , you can take a look on this closed PR : https://github.com/Smile-SA/smile-magento-elasticsearch/pull/48

The guy submitting it proposes a way to have such a "partial" usage of the module for search results only.

Our suite is meant to replace the standard search engine, which indeed means that when installing the module, you plan to use it for layered navigation in categories too.

We do not plan to support such a partial integration and did not merge this PR. But feel free to give it a chance to see if it fits your needs.

Regards,

**Comment by opencubicles** [comment] 2016-09-01 12:49
@romainruaud  thanks for your quick response. 

The only reason we need partial integration is that for some weird reasons for some category ids in our store we see irrelevant products listing which aren't related to the category id at all. 

We even did re-indexing for all indexes but that didn't help. 

Any related issue ?

**Comment by romainruaud** [comment] 2016-10-11 07:33
Hello @opencubicles . I close this issue since your initial question has been answered. If you are still facing issues on categories, do not hesitate to open a news issues with details about how to reproduce it.
Best regards.

**Closed as completed by romainruaud** 2016-10-11 07:33 UTC
